# 服务名称
spring:
# 在eureka中注册的名称
  application:
    name: eureka-client-provider
#数据源
  datasource:
    name: test
    url: jdbc:mysql://106.12.43.192:3306/test?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&characterEncoding=utf-8
#    106.13.41.237 王冲百度云
#    106..12.43.232百度云
#    url: jdbc:mysql://106.13.41.237:3306/test?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: 123456
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapperLocations: classpath:mapper/*.xml

# 服务提供者端口号
server:
  port: 7002

# 配置Eureka Server 信息
eureka:
  client:
    service-url:
#      defaultZone: http://localhost:8761/eureka/
#       106.13.41.237
      defaultZone: http://106.12.43.192:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: 106.12.43.192:${server.port}